version: 0.1
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml 
                                   --s3-bucket serverless-cicd-lxgzmy 
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - outputSamTemplate.yaml
