AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Parameters:
  bucket:
    Type: String
    Default: "serverless-cicd-lxgzmy"
  bucketKey:
    Type: String
    Default: "b4a22cff1c0d2e789c64ffe9566247a5"
Resources:
  mycicdstackTimeFunctionQQ8HEDFP1V63:
    Properties:
      AutoPublishAlias: Live
      CodeUri: 
        Bucket: !Ref bucket
        Key: !Ref bucketKey
      DeploymentPreference:
        Alarms: null
        Type: Linear10PercentEvery1Minute
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
