AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./

      AutoPublishAlias: live

      DeploymentPreference:
        Type: Canary10Percent10Minutes 
        Alarms:
         # A list of alarms that you want to monitor
          #- !Ref AliasErrorMetricGreaterThanZeroAlarm
          #- !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
      Hooks:
        # Validation Lambda functions that are run before & after traffic shifting
        #PreTraffic: !Ref PreTrafficLambdaFunction
        #PostTraffic: !Ref PostTrafficLambdaFunction
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
