AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  mycicdstackTimeFunctionQQ8HEDFP1V63:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      AutoPublishAlias: live

      DeploymentPreference:
        Type: Canary10Percent10Minutes 
        Alarms:
          # A list of alarms that you want to monitor
          # - !Ref AliasErrorMetricGreaterThanZeroAlarm
          # - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
