AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  mycicdstackTimeFunctionQQ8HEDFP1V63:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      AutoPublishAlias: Live

      DeploymentPreference:
        Type: Linear10PercentEvery1Minute 
        Alarms:
          # A list of alarms that you want to monitor
          # - !Ref AliasErrorMetricGreaterThanZeroAlarm
  # AliasErrorMetricGreaterThanZeroAlarm:
  #   #DependsOn: mycicdstackTimeFunctionQQ8HEDFP1V63.Alias
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmName: !Sub aahelloworld-safemode-alias-${HelloWorldFunction}
  #     AlarmDescription: "pre-deployment alarm to check for errors in the function"
  #     #AlarmActions:
  #     #  - !Ref AlarmTopic
  #     ComparisonOperator: GreaterThanOrEqualToThreshold
  #     Dimensions:
  #       - Name: Alias
  #         Value: !Ref HelloWorldFunction.Alias
  #     EvaluationPeriods: 1
  #     MetricName: Errors
  #     Namespace: AWS/Lambda
  #     Period: '60'
  #     Statistic: Sum
  #     Threshold: '1'

