AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  mycicdstack-mycicdstackTimeFunctionQQ8HEDFP1V63-1RI2OR4CV21C8:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      AutoPublishAlias: Live

      DeploymentPreference:
        Type: Linear10PercentEvery1Minute 
        Alarms:
          # A list of alarms that you want to monitor
          # - !Ref AliasErrorMetricGreaterThanZeroAlarm
          # - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
